name: irem-backend
environment: testing
enabled: true

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/iremdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
    api-docs:
      path: /api-docs